import React, { useRef, useMemo, Suspense } from 'react';
import { useFrame } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { getMaritimeGlobeCurve, GLOBE_RADIUS } from '../../utils/globeCoordinates';
import { HERO_CONFIG } from '../../config/heroConfig';
import { ErrorBoundary } from '../common/ErrorBoundary';
import { PhotorealisticBulkCarrier } from '../models/PhotorealisticBulkCarrier';

/**
 * GLTF Model Normalizer & PBR Material Enhancer
 */
const NormalizedGLTFShip = ({ path }) => {
  const { scene } = useGLTF(path);

  const normalizedScene = useMemo(() => {
    const clone = scene.clone();
    
    // Compute accurate bounding box
    const box = new THREE.Box3().setFromObject(clone);
    const size = new THREE.Vector3();
    box.getSize(size);
    const center = new THREE.Vector3();
    box.getCenter(center);

    // Physical bulk carrier scale: length ≈ 0.16 on globe radius 5.0
    const maxDim = Math.max(size.x, size.y, size.z);
    const targetScale = maxDim > 0 ? 0.155 / maxDim : 0.085;

    clone.scale.setScalar(targetScale);
    
    // Center vessel at waterline (draft submerged, deck above)
    clone.position.x = -center.x * targetScale;
    clone.position.y = -box.min.y * targetScale - 0.004;
    clone.position.z = -center.z * targetScale;

    // Enhance all mesh materials for realism
    clone.traverse((child) => {
      if (child.isMesh) {
        child.castShadow = true;
        child.receiveShadow = true;
        if (child.material) {
          child.material.roughness = Math.max(0.7, child.material.roughness || 0.75);
          child.material.metalness = Math.min(0.2, child.material.metalness || 0.1);
        }
      }
    });

    return clone;
  }, [scene]);

  return <primitive object={normalizedScene} />;
};

/**
 * Photorealistic Kelvin Wake Simulation
 * Authentic V-angle dispersion foam trail generated by a heavy ship at sea
 */
const PhotorealisticWake = () => {
  return (
    <group position={[0, 0.002, -0.075]} rotation={[-Math.PI / 2, 0, 0]}>
      {/* Central propeller wash foam */}
      <mesh position={[0, 0.035, 0]}>
        <planeGeometry args={[0.024, 0.10]} />
        <meshBasicMaterial
          color="#cbd5e1"
          transparent
          opacity={0.14}
          blending={THREE.AdditiveBlending}
        />
      </mesh>

      {/* Port divergent wake feather */}
      <mesh position={[-0.016, 0.07, 0]} rotation={[0, 0, 0.13]}>
        <planeGeometry args={[0.012, 0.16]} />
        <meshBasicMaterial
          color="#94a3b8"
          transparent
          opacity={0.10}
          blending={THREE.AdditiveBlending}
        />
      </mesh>

      {/* Starboard divergent wake feather */}
      <mesh position={[0.016, 0.07, 0]} rotation={[0, 0, -0.13]}>
        <planeGeometry args={[0.012, 0.16]} />
        <meshBasicMaterial
          color="#94a3b8"
          transparent
          opacity={0.10}
          blending={THREE.AdditiveBlending}
        />
      </mesh>
    </group>
  );
};

/**
 * ShipOnGlobe Component
 * Positions and animates the commercial bulk carrier on the globe surface with heavy vessel physics.
 */
export const ShipOnGlobe = ({ progress = 0 }) => {
  const shipGroupRef = useRef();
  const curve = useMemo(() => getMaritimeGlobeCurve(GLOBE_RADIUS, 0.008), []);
  const config = HERO_CONFIG.models.ship;

  useFrame((state) => {
    if (!shipGroupRef.current) return;

    // Ship travel progression (deliberate, steady, heavy vessel cruising)
    const vesselT = Math.min(1.0, Math.max(0.0, (progress - 0.08) / 0.82));
    const currentPos = curve.getPoint(vesselT);
    const nextPos = curve.getPoint(Math.min(1.0, vesselT + 0.005));

    // Calculate normal (up from globe center) and tangent along route
    const normal = currentPos.clone().normalize();
    const tangent = nextPos.clone().sub(currentPos).normalize();
    const bitangent = new THREE.Vector3().crossVectors(normal, tangent).normalize();

    // Tangential rotation matrix (flush with spherical water surface)
    const rotMatrix = new THREE.Matrix4().makeBasis(bitangent, normal, tangent);

    // Heavy ship buoyancy in ocean swells (restrained heave, pitch, and roll)
    const t = state.clock.getElapsedTime();
    const heave = Math.sin(t * 1.0 + vesselT * 6) * 0.0012;
    const finalPos = currentPos.clone().add(normal.clone().multiplyScalar(heave));

    shipGroupRef.current.position.copy(finalPos);
    shipGroupRef.current.setRotationFromMatrix(rotMatrix);

    // Subtle, realistic marine pitch and roll
    shipGroupRef.current.rotation.x += Math.sin(t * 0.7) * 0.005;
    shipGroupRef.current.rotation.z += Math.cos(t * 0.5) * 0.003;
  });

  return (
    <group ref={shipGroupRef} name="ShipOnGlobeGroup">
      <ErrorBoundary fallback={<PhotorealisticBulkCarrier scale={0.085} />}>
        <Suspense fallback={<PhotorealisticBulkCarrier scale={0.085} />}>
          <NormalizedGLTFShip path={config.path} />
        </Suspense>
      </ErrorBoundary>

      <PhotorealisticWake />
    </group>
  );
};
